Algoritmo "Calculo_area_trapezio"
//meu problema
//como calcular a area do trapezio
//base maior = 8.0
//base menor = 6.0
//altura = 5.0

Var
//1 passo entrada dos dados(variaveis)
baseMenor, baseMaior, h ,area : real

Inicio
// 2 passo processamento dos dados (calculos)

baseMenor <- 6.0
baseMaior <- 8.0
h <- 5.0
area <- (baseMenor + baseMaior) / 2.0 * h;

//3 passo saida dos dados
escreval("O resulta da area do trapezéio é: ",area)


Fimalgoritmo
