Algoritmo "Calculo_area_trapezio"
//meu problema
//como calcular a area do trapezio
//base maior = 8
//base menor = 6
//altura = 5

Var
//1 passo entrada dos dados(variaveis)
baseMenor, baseMaior, h ,area : real

Inicio
// 2 passo processamento dos dados (calculos)

baseMenor <- 6
baseMaior <- 8
h <- 5
area <- (baseMenor + baseMaior) / 2.0 * h;

//3 passo saida dos dados
escreval("O resulta da area do trapezéio é: ",area)


Fimalgoritmo